### PR TITLE
Hgcwa stats

### PR DESCRIPTION
**Pull request by roed314**
It will be much easier to see my changes if you pull in upstream master.

### CODE REVIEW

**Comment by jenpaulhus** [comment]
@roed314 Sorry, I don't understand exactly what you are saying here.  Are you saying pull upstream first and then merge your changes, or merge your changes and then pull upstream master, or something else?

**Comment by roed314** [comment]
If you pull upstream first into your branch, then you'll be able to see the actual changes that I'm suggesting.  Right now my changes are drowned out by the 56 files of changes from other changes currently in master but not your branch.

**Comment by jenpaulhus** [comment]
I pulled upstream and then pushed that update to my statsfix branch,  and then I merged your branch locally and got no merge conflicts (despite the fact that this webpage currently claims there are conflicts).  

However, when I go to localhost and click on "further statistics", I'm now getting an error on line 212 of my local copy of  main.py  which is the return render_template command in the stats page:
`return render_template("hgcwa-stats.html", info=HGCWAstats(), credit=credit, title=title, learnmore=learnmore_list(), bread=bread)
`

Sometimes it's a "Too many open files" error and the traceback is below.  I also got a different error once but I can't reproduce that error at the moment.



```
Traceback (most recent call last):
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/app.py", line 31, in __call__
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/higher_genus_w_automorphisms/main.py", line 212, in statistics
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/templating.py", line 136, in render_template
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 838, in update_template_context
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/app.py", line 556, in add_colors
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/utils/config.py", line 54, in __init__
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/utils/config.py", line 32, in abs_path_lmfdb
    
OSError: [Errno 24] Too many open files


```

**Comment by jenpaulhus** [comment]
Here's the other errors I get

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 898, in set
    
KeyError: 'core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/app.py", line 31, in __call__
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/higher_genus_w_automorphisms/main.py", line 212, in statistics
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/templating.py", line 136, in render_template
    
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 838, in update_template_context
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/app.py", line 556, in add_colors
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/utils/config.py", line 234, in __init__
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/backend/config.py", line 190, in __init__
    
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1198, in set
    
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 900, in set
    
configparser.NoSectionError: No section: 'core'
```


And


```
Traceback (most recent call last):
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/app.py", line 31, in __call__
    return self.app(environ, start_response)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/higher_genus_w_automorphisms/main.py", line 212, in statistics
    return render_template("hgcwa-stats.html", info=HGCWAstats(), credit=credit, title=title, learnmore=learnmore_list(), bread=bread)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/higher_genus_w_automorphisms/templates/hgcwa-stats.html", line 1, in top-level template code
    {% extends 'display_stats.html' %}
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/templates/display_stats.html", line 1, in top-level template code
    {% extends 'homepage.html' %}
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/templates/homepage.html", line 19, in top-level template code
    <div class="{{ [L,'nodisplay','code','codebox'] | join(' ')}}">{% for line in lines %}{{prompt}}:&nbsp;{{line}}<br /><div style="margin: 0; padding: 0; height: 0;">&nbsp;</div>{# this div is a workaround for a copy-tex bug where if a code block followed a hidden code block followed by math was selected and copied the hidden block would be also it is important that it has display: block #}{% endfor %}</div>
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/templates/base.html", line 135, in top-level template code
    {% block body -%}{%- endblock body %}
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/templates/homepage.html", line 244, in block "body"
    {% block content -%}
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/templates/display_stats.html", line 16, in block "content"
    {% for d in info.distributions %}
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "sage/misc/lazy_attribute.pyx", line 127, in sage.misc.lazy_attribute._lazy_attribute.__get__ (build/cythonized/sage/misc/lazy_attribute.c:1958)
    
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/utils/display_stats.py", line 636, in distributions
    return [self.prep(attr) for attr in self.stat_list]
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/utils/display_stats.py", line 636, in <listcomp>
    return [self.prep(attr) for attr in self.stat_list]
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/utils/display_stats.py", line 615, in prep
    data = self.display_data(**attr)
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/utils/display_stats.py", line 527, in display_data
    headers, counts = table._get_values_counts(cols, constraint, split_list=split_list, formatter=formatter, query_formatter=query_formatter, base_url=base_url, buckets=buckets)
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/backend/statstable.py", line 1590, in _get_values_counts
    self.add_stats(cols, constraint, split_list=split_list)
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/backend/statstable.py", line 1182, in add_stats
    values_list=True,
  File "/Users/lisavi/jenlmfdb/lmfdb/lmfdb/backend/base.py", line 306, in _execute
    execute_values(cur, query.as_string(self.conn), values, template)
  File "/Users/lisavi/sage/sage-9.1/local/lib/python3.7/site-packages/psycopg2/extras.py", line 1289, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.ReadOnlySqlTransaction: cannot execute INSERT in a read-only transaction
```

**Comment by roed314** [comment]
I'm just submitting this as another PR to the main repo.  The first error you got is one I've seen as well; Edgar says it's a problem with OS X and you should run `ulimit -n 8192` to increase the number of available file handles.  The second looks like a problem with your configuration file, but I'm not sure what the issue is.  The third is because you're not logged in as editor but it's trying to update stats.  I'm not sure why it would be doing that....

**Pull request closed without merging**
